language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - sudo apt-get install pokerth-server
before_script:
  - sudo ln -s /usr/games/pokerth_server /usr/local/bin/pokerth_server
script:
  - python setup.py test
after_success:
  - coveralls

