language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - sudo apt-get install pokerth-server
script:
  - python setup.py test
after_success:
  - coveralls

