language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - wget https://launchpad.net/~pkg-games/+archive/ppa/+files/pokerth-server_1.0.1-2~ppa1~precise1_amd64.deb
  - sudo dpkg --install pokerth-server_1.0.1-2~ppa1~precise1_amd64.deb
before_script:
  - sudo ln -s /usr/games/pokerth_server /usr/local/bin/pokerth_server
script:
  - python setup.py test
after_success:
  - coveralls

